/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "I2C.h"
#include "I2C_I2C.h"
#include "I2C_PINS.h"
#include "I2C_I2C_PVT.h"
#include "I2C_PVT.h"
#include "I2C_BOOT.h"
#include "SPI.h"
#include "SPI_SPI_UART.h"
#include "SPI_PINS.h"
#include "SPI_SPI_UART_PVT.h"
#include "SPI_PVT.h"
#include "SPI_BOOT.h"
#include "NRF_IRQ.h"
#include "NRF_IRQ_aliases.h"
#include "NRF_SS.h"
#include "NRF_SS_aliases.h"
#include "NRF_CSN.h"
#include "NRF_CSN_aliases.h"
#include "OPT_IRQ.h"
#include "OPT_IRQ_aliases.h"
#include "TEMP_IRQ.h"
#include "TEMP_IRQ_aliases.h"
#include "CRIT_TEMP_IRQ.h"
#include "CRIT_TEMP_IRQ_aliases.h"
#include "Led.h"
#include "Led_aliases.h"
#include "Load.h"
#include "Load_aliases.h"
#include "Button.h"
#include "Button_aliases.h"
#include "External_ISR.h"
#include "Timer.h"
#include "Clock.h"
#include "Timer_RTOS_ISR.h"
#include "I2C_SCBCLK.h"
#include "I2C_sda.h"
#include "I2C_sda_aliases.h"
#include "I2C_scl.h"
#include "I2C_scl_aliases.h"
#include "I2C_SCB_IRQ.h"
#include "SPI_SCBCLK.h"
#include "SPI_sclk_m.h"
#include "SPI_sclk_m_aliases.h"
#include "SPI_miso_m.h"
#include "SPI_miso_m_aliases.h"
#include "SPI_mosi_m.h"
#include "SPI_mosi_m_aliases.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyLFClk.h"

/*[]*/

